

sass:
  sass_dir: assets/css

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap

title: "挑战年薪30万-java开发" # the name of your site, e.g. ACME Corp.
tagline: "An awesome tagline"
email: "your.email@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
author: 坏孩子是你啊
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/javago" # the subpath of your site, e.g. /blog
google_analytics: UA-111111111-1
twitter:
  username:
  card: summary #keep this to generate a twitter share card

# 高亮的语法处理配置
highlighter: rouge
markdown: kramdown

redcarpet:
  extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]

kramdown:
  input:         GFM
  auto_ids:      true
  auto_id_prefix: 'id-'
  syntax_highlighter: rouge
